/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Kontaktseite = {
  _id: string;
  _type: "kontaktseite";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  kopf: SektionsKopf;
  formularHinweis?: string;
  ablauf?: Array<string>;
  seo?: Seo;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  titel?: string;
  beschreibung?: string;
  bild?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  vonSucheAusschliessen?: boolean;
};

export type SektionsKopf = {
  _type: "sektionsKopf";
  kennzeichnung?: string;
  titel: string;
  text?: string;
};

export type UeberSeite = {
  _id: string;
  _type: "ueberSeite";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  kopf: SektionsKopf;
  portrait?: BildMitText;
  text?: Inhaltstext;
  grundsaetze?: Array<
    {
      _key: string;
    } & Merkmal
  >;
  seo?: Seo;
};

export type Inhaltstext = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & BildMitText)
>;

export type BildMitText = {
  _type: "bildMitText";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt: string;
  bildunterschrift?: string;
};

export type Referenzseite = {
  _id: string;
  _type: "referenzseite";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  kopf: SektionsKopf;
  platzhalterHinweis?: string;
  seo?: Seo;
};

export type Leistungsseite = {
  _id: string;
  _type: "leistungsseite";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  kopf: SektionsKopf;
  preishinweis?: string;
  ablaufKopf?: SektionsKopf;
  fragenKopf?: SektionsKopf;
  seo?: Seo;
};

export type Startseite = {
  _id: string;
  _type: "startseite";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  kennzeichnung?: string;
  ueberschrift: string;
  hervorhebung?: string;
  einleitung: string;
  hauptaktion: Aktion;
  nebenaktion?: Aktion;
  kennzahlen?: Array<
    {
      _key: string;
    } & Kennzahl
  >;
  ausgangslage?: SektionsKopf;
  maengel?: Array<string>;
  loesung?: SektionsKopf;
  vorteile?: Array<
    {
      _key: string;
    } & Merkmal
  >;
  branchenKopf?: SektionsKopf;
  leistungenKopf?: SektionsKopf;
  ablaufKopf?: SektionsKopf;
  referenzenKopf?: SektionsKopf;
  medienKopf?: SektionsKopf;
  medienAnzeigen?: boolean;
  schlussKopf?: SektionsKopf;
  schlussAktion?: Aktion;
  seo?: Seo;
};

export type Aktion = {
  _type: "aktion";
  beschriftung: string;
  ziel: string;
};

export type Grundeinstellungen = {
  _id: string;
  _type: "grundeinstellungen";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  claim?: string;
  verfuegbarkeit?: string;
  laufband?: Array<string>;
  telefon: string;
  email: string;
  erreichbarkeit?: string;
  antwortzeit?: string;
  inhaber: string;
  strasse: string;
  plz: string;
  ort: string;
  land?: string;
  umsatzsteuerId?: string;
  kleinunternehmer?: boolean;
  seo?: Seo;
};

export type Rechtstext = {
  _id: string;
  _type: "rechtstext";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titel: string;
  slug: Slug;
  stand?: string;
  inhalt: Inhaltstext;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Arbeitsschritt = {
  _id: string;
  _type: "arbeitsschritt";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titel: string;
  text: string;
  dauer?: string;
  aufwandKunde?: string;
  reihenfolge: number;
};

export type Frage = {
  _id: string;
  _type: "frage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  frage: string;
  antwort: Inhaltstext;
  reihenfolge: number;
};

export type ReferenzReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "referenz";
};

export type Stimme = {
  _id: string;
  _type: "stimme";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  zitat: string;
  name: string;
  rolle: string;
  portrait?: BildMitText;
  referenz?: ReferenzReference;
  reihenfolge: number;
};

export type BrancheReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "branche";
};

export type LeistungReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "leistung";
};

export type Referenz = {
  _id: string;
  _type: "referenz";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titel: string;
  slug: Slug;
  status: "live" | "inArbeit" | "platzhalter";
  branche: BrancheReference;
  jahr?: number;
  auftrag: string;
  leistungen?: Array<
    {
      _key: string;
    } & LeistungReference
  >;
  ergebnisse?: Array<
    {
      _key: string;
    } & Kennzahl
  >;
  bildNachher?: BildMitText;
  bildVorher?: BildMitText;
  adresse?: string;
  beschreibung?: Inhaltstext;
  reihenfolge: number;
};

export type Branche = {
  _id: string;
  _type: "branche";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titel: string;
  slug: Slug;
  beispiele: Array<string>;
  beduerfnis: string;
  material: "beton" | "holz" | "stahl" | "daemmung";
  reihenfolge: number;
};

export type Leistung = {
  _id: string;
  _type: "leistung";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  titel: string;
  slug: Slug;
  bereich: "website" | "sichtbarkeit" | "betreuung" | "medien";
  versprechen: string;
  teaser: string;
  umfang?: Array<string>;
  beschreibung?: Inhaltstext;
  reihenfolge: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Merkmal = {
  _type: "merkmal";
  titel: string;
  text: string;
};

export type Kennzahl = {
  _type: "kennzahl";
  wert: string;
  label: string;
  erlaeuterung?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Kontaktseite
  | SanityImageAssetReference
  | Seo
  | SektionsKopf
  | UeberSeite
  | Inhaltstext
  | BildMitText
  | Referenzseite
  | Leistungsseite
  | Startseite
  | Aktion
  | Grundeinstellungen
  | Rechtstext
  | Slug
  | Arbeitsschritt
  | Frage
  | ReferenzReference
  | Stimme
  | BrancheReference
  | LeistungReference
  | Referenz
  | Branche
  | Leistung
  | SanityImageCrop
  | SanityImageHotspot
  | Merkmal
  | Kennzahl
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/sanity/lib/queries.ts
// Variable: GRUNDEINSTELLUNGEN_QUERY
// Query: *[_id == "grundeinstellungen"][0]{    name,    claim,    verfuegbarkeit,    "laufband": coalesce(laufband, []),    telefon,    email,    erreichbarkeit,    antwortzeit,    inhaber,    strasse,    plz,    ort,    land,    umsatzsteuerId,    kleinunternehmer,    seo { titel, beschreibung, bild { ..., alt, bildunterschrift, asset }, vonSucheAusschliessen }  }
export type GRUNDEINSTELLUNGEN_QUERY_RESULT =
  | {
      name: null;
      claim: null;
      verfuegbarkeit: null;
      laufband: Array<never>;
      telefon: null;
      email: null;
      erreichbarkeit: null;
      antwortzeit: null;
      inhaber: null;
      strasse: null;
      plz: null;
      ort: null;
      land: null;
      umsatzsteuerId: null;
      kleinunternehmer: null;
      seo: null;
    }
  | {
      name: null;
      claim: null;
      verfuegbarkeit: null;
      laufband: Array<never>;
      telefon: null;
      email: null;
      erreichbarkeit: null;
      antwortzeit: null;
      inhaber: null;
      strasse: null;
      plz: null;
      ort: null;
      land: null;
      umsatzsteuerId: null;
      kleinunternehmer: null;
      seo: {
        titel: string | null;
        beschreibung: string | null;
        bild: {
          asset: SanityImageAssetReference | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          alt: null;
          bildunterschrift: null;
        } | null;
        vonSucheAusschliessen: boolean | null;
      } | null;
    }
  | {
      name: string;
      claim: null;
      verfuegbarkeit: null;
      laufband: Array<never>;
      telefon: null;
      email: null;
      erreichbarkeit: null;
      antwortzeit: null;
      inhaber: null;
      strasse: null;
      plz: null;
      ort: null;
      land: null;
      umsatzsteuerId: null;
      kleinunternehmer: null;
      seo: null;
    }
  | {
      name: string;
      claim: string | null;
      verfuegbarkeit: string | null;
      laufband: Array<string> | Array<never>;
      telefon: string;
      email: string;
      erreichbarkeit: string | null;
      antwortzeit: string | null;
      inhaber: string;
      strasse: string;
      plz: string;
      ort: string;
      land: string | null;
      umsatzsteuerId: string | null;
      kleinunternehmer: boolean | null;
      seo: {
        titel: string | null;
        beschreibung: string | null;
        bild: {
          asset: SanityImageAssetReference | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          alt: null;
          bildunterschrift: null;
        } | null;
        vonSucheAusschliessen: boolean | null;
      } | null;
    }
  | null;

// Source: ../src/sanity/lib/queries.ts
// Variable: BRANCHEN_QUERY
// Query: *[_type == "branche"] | order(reihenfolge asc){    _id,    titel,    "slug": slug.current,    "beispiele": coalesce(beispiele, []),    beduerfnis,    material  }
export type BRANCHEN_QUERY_RESULT = Array<{
  _id: string;
  titel: string;
  slug: string;
  beispiele: Array<string>;
  beduerfnis: string;
  material: "beton" | "daemmung" | "holz" | "stahl";
}>;

// Source: ../src/sanity/lib/queries.ts
// Variable: LEISTUNGEN_QUERY
// Query: *[_type == "leistung"] | order(reihenfolge asc){    _id,    titel,    "slug": slug.current,    bereich,    versprechen,    teaser,    "umfang": coalesce(umfang, []),    "beschreibung": coalesce(beschreibung, [])  }
export type LEISTUNGEN_QUERY_RESULT = Array<{
  _id: string;
  titel: string;
  slug: string;
  bereich: "betreuung" | "medien" | "sichtbarkeit" | "website";
  versprechen: string;
  teaser: string;
  umfang: Array<string> | Array<never>;
  beschreibung: Array<never> | Inhaltstext;
}>;

// Source: ../src/sanity/lib/queries.ts
// Variable: ARBEITSSCHRITTE_QUERY
// Query: *[_type == "arbeitsschritt"] | order(reihenfolge asc){    _id,    titel,    text,    dauer,    aufwandKunde  }
export type ARBEITSSCHRITTE_QUERY_RESULT = Array<{
  _id: string;
  titel: string;
  text: string;
  dauer: string | null;
  aufwandKunde: string | null;
}>;

// Source: ../src/sanity/lib/queries.ts
// Variable: REFERENZEN_QUERY
// Query: *[_type == "referenz"] | order(reihenfolge asc){    _id,    titel,    "slug": slug.current,    status,    jahr,    auftrag,    adresse,    branche->{ titel, material },    "ergebnisse": coalesce(ergebnisse[] { _key, wert, label, erlaeuterung }, []),    bildNachher { ..., alt, bildunterschrift, asset },    bildVorher { ..., alt, bildunterschrift, asset },    "beschreibung": coalesce(beschreibung, [])  }
export type REFERENZEN_QUERY_RESULT = Array<{
  _id: string;
  titel: string;
  slug: string;
  status: "inArbeit" | "live" | "platzhalter";
  jahr: number | null;
  auftrag: string;
  adresse: string | null;
  branche: {
    titel: string;
    material: "beton" | "daemmung" | "holz" | "stahl";
  };
  ergebnisse:
    | Array<{
        _key: string;
        wert: string;
        label: string;
        erlaeuterung: string | null;
      }>
    | Array<never>;
  bildNachher: {
    _type: "bildMitText";
    asset: SanityImageAssetReference | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    bildunterschrift: string | null;
  } | null;
  bildVorher: {
    _type: "bildMitText";
    asset: SanityImageAssetReference | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    bildunterschrift: string | null;
  } | null;
  beschreibung: Array<never> | Inhaltstext;
}>;

// Source: ../src/sanity/lib/queries.ts
// Variable: STIMMEN_QUERY
// Query: *[_type == "stimme"] | order(reihenfolge asc){    _id,    zitat,    name,    rolle,    portrait { ..., alt, bildunterschrift, asset }  }
export type STIMMEN_QUERY_RESULT = Array<{
  _id: string;
  zitat: string;
  name: string;
  rolle: string;
  portrait: {
    _type: "bildMitText";
    asset: SanityImageAssetReference | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    bildunterschrift: string | null;
  } | null;
}>;

// Source: ../src/sanity/lib/queries.ts
// Variable: FRAGEN_QUERY
// Query: *[_type == "frage"] | order(reihenfolge asc){    _id,    frage,    "antwort": coalesce(antwort, [])  }
export type FRAGEN_QUERY_RESULT = Array<{
  _id: string;
  frage: string;
  antwort: Inhaltstext;
}>;

// Source: ../src/sanity/lib/queries.ts
// Variable: STARTSEITE_QUERY
// Query: *[_id == "startseite"][0]{    kennzeichnung,    ueberschrift,    hervorhebung,    einleitung,    hauptaktion { beschriftung, ziel },    nebenaktion { beschriftung, ziel },    "kennzahlen": coalesce(kennzahlen[] { _key, wert, label, erlaeuterung }, []),    ausgangslage { kennzeichnung, titel, text },    "maengel": coalesce(maengel, []),    loesung { kennzeichnung, titel, text },    "vorteile": coalesce(vorteile[] { _key, titel, text }, []),    branchenKopf { kennzeichnung, titel, text },    leistungenKopf { kennzeichnung, titel, text },    ablaufKopf { kennzeichnung, titel, text },    referenzenKopf { kennzeichnung, titel, text },    medienKopf { kennzeichnung, titel, text },    medienAnzeigen,    schlussKopf { kennzeichnung, titel, text },    schlussAktion { beschriftung, ziel },    seo { titel, beschreibung, bild { ..., alt, bildunterschrift, asset }, vonSucheAusschliessen }  }
export type STARTSEITE_QUERY_RESULT =
  | {
      kennzeichnung: null;
      ueberschrift: null;
      hervorhebung: null;
      einleitung: null;
      hauptaktion: null;
      nebenaktion: null;
      kennzahlen: Array<never>;
      ausgangslage: null;
      maengel: Array<never>;
      loesung: null;
      vorteile: Array<never>;
      branchenKopf: null;
      leistungenKopf: null;
      ablaufKopf: null;
      referenzenKopf: null;
      medienKopf: null;
      medienAnzeigen: null;
      schlussKopf: null;
      schlussAktion: null;
      seo: null;
    }
  | {
      kennzeichnung: null;
      ueberschrift: null;
      hervorhebung: null;
      einleitung: null;
      hauptaktion: null;
      nebenaktion: null;
      kennzahlen: Array<never>;
      ausgangslage: null;
      maengel: Array<never>;
      loesung: null;
      vorteile: Array<never>;
      branchenKopf: null;
      leistungenKopf: null;
      ablaufKopf: null;
      referenzenKopf: null;
      medienKopf: null;
      medienAnzeigen: null;
      schlussKopf: null;
      schlussAktion: null;
      seo: {
        titel: string | null;
        beschreibung: string | null;
        bild: {
          asset: SanityImageAssetReference | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          alt: null;
          bildunterschrift: null;
        } | null;
        vonSucheAusschliessen: boolean | null;
      } | null;
    }
  | {
      kennzeichnung: null;
      ueberschrift: null;
      hervorhebung: null;
      einleitung: null;
      hauptaktion: null;
      nebenaktion: null;
      kennzahlen: Array<never>;
      ausgangslage: null;
      maengel: Array<never>;
      loesung: null;
      vorteile: Array<never>;
      branchenKopf: null;
      leistungenKopf: null;
      ablaufKopf: {
        kennzeichnung: string | null;
        titel: string;
        text: string | null;
      } | null;
      referenzenKopf: null;
      medienKopf: null;
      medienAnzeigen: null;
      schlussKopf: null;
      schlussAktion: null;
      seo: {
        titel: string | null;
        beschreibung: string | null;
        bild: {
          asset: SanityImageAssetReference | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          alt: null;
          bildunterschrift: null;
        } | null;
        vonSucheAusschliessen: boolean | null;
      } | null;
    }
  | {
      kennzeichnung: string | null;
      ueberschrift: string;
      hervorhebung: string | null;
      einleitung: string;
      hauptaktion: {
        beschriftung: string;
        ziel: string;
      };
      nebenaktion: {
        beschriftung: string;
        ziel: string;
      } | null;
      kennzahlen:
        | Array<{
            _key: string;
            wert: string;
            label: string;
            erlaeuterung: string | null;
          }>
        | Array<never>;
      ausgangslage: {
        kennzeichnung: string | null;
        titel: string;
        text: string | null;
      } | null;
      maengel: Array<string> | Array<never>;
      loesung: {
        kennzeichnung: string | null;
        titel: string;
        text: string | null;
      } | null;
      vorteile:
        | Array<{
            _key: string;
            titel: string;
            text: string;
          }>
        | Array<never>;
      branchenKopf: {
        kennzeichnung: string | null;
        titel: string;
        text: string | null;
      } | null;
      leistungenKopf: {
        kennzeichnung: string | null;
        titel: string;
        text: string | null;
      } | null;
      ablaufKopf: {
        kennzeichnung: string | null;
        titel: string;
        text: string | null;
      } | null;
      referenzenKopf: {
        kennzeichnung: string | null;
        titel: string;
        text: string | null;
      } | null;
      medienKopf: {
        kennzeichnung: string | null;
        titel: string;
        text: string | null;
      } | null;
      medienAnzeigen: boolean | null;
      schlussKopf: {
        kennzeichnung: string | null;
        titel: string;
        text: string | null;
      } | null;
      schlussAktion: {
        beschriftung: string;
        ziel: string;
      } | null;
      seo: {
        titel: string | null;
        beschreibung: string | null;
        bild: {
          asset: SanityImageAssetReference | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          alt: null;
          bildunterschrift: null;
        } | null;
        vonSucheAusschliessen: boolean | null;
      } | null;
    }
  | null;

// Source: ../src/sanity/lib/queries.ts
// Variable: LEISTUNGSSEITE_QUERY
// Query: *[_id == "leistungsseite"][0]{    kopf { kennzeichnung, titel, text },    preishinweis,    ablaufKopf { kennzeichnung, titel, text },    fragenKopf { kennzeichnung, titel, text },    seo { titel, beschreibung, bild { ..., alt, bildunterschrift, asset }, vonSucheAusschliessen }  }
export type LEISTUNGSSEITE_QUERY_RESULT =
  | {
      kopf: null;
      preishinweis: null;
      ablaufKopf: null;
      fragenKopf: null;
      seo: null;
    }
  | {
      kopf: null;
      preishinweis: null;
      ablaufKopf: null;
      fragenKopf: null;
      seo: {
        titel: string | null;
        beschreibung: string | null;
        bild: {
          asset: SanityImageAssetReference | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          alt: null;
          bildunterschrift: null;
        } | null;
        vonSucheAusschliessen: boolean | null;
      } | null;
    }
  | {
      kopf: {
        kennzeichnung: string | null;
        titel: string;
        text: string | null;
      };
      preishinweis: null;
      ablaufKopf: null;
      fragenKopf: null;
      seo: {
        titel: string | null;
        beschreibung: string | null;
        bild: {
          asset: SanityImageAssetReference | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          alt: null;
          bildunterschrift: null;
        } | null;
        vonSucheAusschliessen: boolean | null;
      } | null;
    }
  | {
      kopf: null;
      preishinweis: null;
      ablaufKopf: {
        kennzeichnung: string | null;
        titel: string;
        text: string | null;
      } | null;
      fragenKopf: null;
      seo: {
        titel: string | null;
        beschreibung: string | null;
        bild: {
          asset: SanityImageAssetReference | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          alt: null;
          bildunterschrift: null;
        } | null;
        vonSucheAusschliessen: boolean | null;
      } | null;
    }
  | {
      kopf: {
        kennzeichnung: string | null;
        titel: string;
        text: string | null;
      };
      preishinweis: string | null;
      ablaufKopf: {
        kennzeichnung: string | null;
        titel: string;
        text: string | null;
      } | null;
      fragenKopf: {
        kennzeichnung: string | null;
        titel: string;
        text: string | null;
      } | null;
      seo: {
        titel: string | null;
        beschreibung: string | null;
        bild: {
          asset: SanityImageAssetReference | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          alt: null;
          bildunterschrift: null;
        } | null;
        vonSucheAusschliessen: boolean | null;
      } | null;
    }
  | null;

// Source: ../src/sanity/lib/queries.ts
// Variable: REFERENZSEITE_QUERY
// Query: *[_id == "referenzseite"][0]{    kopf { kennzeichnung, titel, text },    platzhalterHinweis,    seo { titel, beschreibung, bild { ..., alt, bildunterschrift, asset }, vonSucheAusschliessen }  }
export type REFERENZSEITE_QUERY_RESULT =
  | {
      kopf: null;
      platzhalterHinweis: null;
      seo: null;
    }
  | {
      kopf: null;
      platzhalterHinweis: null;
      seo: {
        titel: string | null;
        beschreibung: string | null;
        bild: {
          asset: SanityImageAssetReference | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          alt: null;
          bildunterschrift: null;
        } | null;
        vonSucheAusschliessen: boolean | null;
      } | null;
    }
  | {
      kopf: {
        kennzeichnung: string | null;
        titel: string;
        text: string | null;
      };
      platzhalterHinweis: null;
      seo: {
        titel: string | null;
        beschreibung: string | null;
        bild: {
          asset: SanityImageAssetReference | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          alt: null;
          bildunterschrift: null;
        } | null;
        vonSucheAusschliessen: boolean | null;
      } | null;
    }
  | {
      kopf: {
        kennzeichnung: string | null;
        titel: string;
        text: string | null;
      };
      platzhalterHinweis: string | null;
      seo: {
        titel: string | null;
        beschreibung: string | null;
        bild: {
          asset: SanityImageAssetReference | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          alt: null;
          bildunterschrift: null;
        } | null;
        vonSucheAusschliessen: boolean | null;
      } | null;
    }
  | null;

// Source: ../src/sanity/lib/queries.ts
// Variable: UEBER_SEITE_QUERY
// Query: *[_id == "ueberSeite"][0]{    kopf { kennzeichnung, titel, text },    portrait { ..., alt, bildunterschrift, asset },    "text": coalesce(text, []),    "grundsaetze": coalesce(grundsaetze[] { _key, titel, text }, []),    seo { titel, beschreibung, bild { ..., alt, bildunterschrift, asset }, vonSucheAusschliessen }  }
export type UEBER_SEITE_QUERY_RESULT =
  | {
      kopf: {
        kennzeichnung: string | null;
        titel: string;
        text: string | null;
      };
      portrait: {
        _type: "bildMitText";
        asset: SanityImageAssetReference | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        bildunterschrift: string | null;
      } | null;
      text: Array<never> | Inhaltstext;
      grundsaetze:
        | Array<{
            _key: string;
            titel: string;
            text: string;
          }>
        | Array<never>;
      seo: {
        titel: string | null;
        beschreibung: string | null;
        bild: {
          asset: SanityImageAssetReference | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          alt: null;
          bildunterschrift: null;
        } | null;
        vonSucheAusschliessen: boolean | null;
      } | null;
    }
  | {
      kopf: null;
      portrait: null;
      text: Array<never>;
      grundsaetze: Array<never>;
      seo: null;
    }
  | {
      kopf: null;
      portrait: null;
      text: string;
      grundsaetze: Array<never>;
      seo: null;
    }
  | {
      kopf: null;
      portrait: null;
      text: Array<never>;
      grundsaetze: Array<never>;
      seo: {
        titel: string | null;
        beschreibung: string | null;
        bild: {
          asset: SanityImageAssetReference | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          alt: null;
          bildunterschrift: null;
        } | null;
        vonSucheAusschliessen: boolean | null;
      } | null;
    }
  | {
      kopf: null;
      portrait: {
        _type: "bildMitText";
        asset: SanityImageAssetReference | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        bildunterschrift: string | null;
      } | null;
      text: Array<never>;
      grundsaetze: Array<never>;
      seo: null;
    }
  | {
      kopf: {
        kennzeichnung: string | null;
        titel: string;
        text: string | null;
      };
      portrait: null;
      text: Array<never>;
      grundsaetze: Array<never>;
      seo: {
        titel: string | null;
        beschreibung: string | null;
        bild: {
          asset: SanityImageAssetReference | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          alt: null;
          bildunterschrift: null;
        } | null;
        vonSucheAusschliessen: boolean | null;
      } | null;
    }
  | null;

// Source: ../src/sanity/lib/queries.ts
// Variable: KONTAKTSEITE_QUERY
// Query: *[_id == "kontaktseite"][0]{    kopf { kennzeichnung, titel, text },    formularHinweis,    "ablauf": coalesce(ablauf, []),    seo { titel, beschreibung, bild { ..., alt, bildunterschrift, asset }, vonSucheAusschliessen }  }
export type KONTAKTSEITE_QUERY_RESULT =
  | {
      kopf: {
        kennzeichnung: string | null;
        titel: string;
        text: string | null;
      };
      formularHinweis: string | null;
      ablauf: Array<string> | Array<never>;
      seo: {
        titel: string | null;
        beschreibung: string | null;
        bild: {
          asset: SanityImageAssetReference | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          alt: null;
          bildunterschrift: null;
        } | null;
        vonSucheAusschliessen: boolean | null;
      } | null;
    }
  | {
      kopf: null;
      formularHinweis: null;
      ablauf: Array<never>;
      seo: null;
    }
  | {
      kopf: null;
      formularHinweis: null;
      ablauf: Array<never>;
      seo: {
        titel: string | null;
        beschreibung: string | null;
        bild: {
          asset: SanityImageAssetReference | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          alt: null;
          bildunterschrift: null;
        } | null;
        vonSucheAusschliessen: boolean | null;
      } | null;
    }
  | {
      kopf: {
        kennzeichnung: string | null;
        titel: string;
        text: string | null;
      };
      formularHinweis: null;
      ablauf: Array<never>;
      seo: {
        titel: string | null;
        beschreibung: string | null;
        bild: {
          asset: SanityImageAssetReference | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          alt: null;
          bildunterschrift: null;
        } | null;
        vonSucheAusschliessen: boolean | null;
      } | null;
    }
  | null;

// Source: ../src/sanity/lib/queries.ts
// Variable: RECHTSTEXT_QUERY
// Query: *[_type == "rechtstext" && slug.current == $slug][0]{    titel,    "slug": slug.current,    stand,    "inhalt": coalesce(inhalt, []),    seo { titel, beschreibung, bild { ..., alt, bildunterschrift, asset }, vonSucheAusschliessen }  }
export type RECHTSTEXT_QUERY_RESULT = {
  titel: string;
  slug: string;
  stand: string | null;
  inhalt: Inhaltstext;
  seo: {
    titel: string | null;
    beschreibung: string | null;
    bild: {
      asset: SanityImageAssetReference | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      alt: null;
      bildunterschrift: null;
    } | null;
    vonSucheAusschliessen: boolean | null;
  } | null;
} | null;

// Source: ../src/sanity/lib/queries.ts
// Variable: RECHTSTEXT_SLUGS_QUERY
// Query: *[_type == "rechtstext" && defined(slug.current)]{ "slug": slug.current }
export type RECHTSTEXT_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_id == "grundeinstellungen"][0]{\n    name,\n    claim,\n    verfuegbarkeit,\n    "laufband": coalesce(laufband, []),\n    telefon,\n    email,\n    erreichbarkeit,\n    antwortzeit,\n    inhaber,\n    strasse,\n    plz,\n    ort,\n    land,\n    umsatzsteuerId,\n    kleinunternehmer,\n    seo { titel, beschreibung, bild { ..., alt, bildunterschrift, asset }, vonSucheAusschliessen }\n  }\n': GRUNDEINSTELLUNGEN_QUERY_RESULT;
    '\n  *[_type == "branche"] | order(reihenfolge asc){\n    _id,\n    titel,\n    "slug": slug.current,\n    "beispiele": coalesce(beispiele, []),\n    beduerfnis,\n    material\n  }\n': BRANCHEN_QUERY_RESULT;
    '\n  *[_type == "leistung"] | order(reihenfolge asc){\n    _id,\n    titel,\n    "slug": slug.current,\n    bereich,\n    versprechen,\n    teaser,\n    "umfang": coalesce(umfang, []),\n    "beschreibung": coalesce(beschreibung, [])\n  }\n': LEISTUNGEN_QUERY_RESULT;
    '\n  *[_type == "arbeitsschritt"] | order(reihenfolge asc){\n    _id,\n    titel,\n    text,\n    dauer,\n    aufwandKunde\n  }\n': ARBEITSSCHRITTE_QUERY_RESULT;
    '\n  *[_type == "referenz"] | order(reihenfolge asc){\n    _id,\n    titel,\n    "slug": slug.current,\n    status,\n    jahr,\n    auftrag,\n    adresse,\n    branche->{ titel, material },\n    "ergebnisse": coalesce(ergebnisse[] { _key, wert, label, erlaeuterung }, []),\n    bildNachher { ..., alt, bildunterschrift, asset },\n    bildVorher { ..., alt, bildunterschrift, asset },\n    "beschreibung": coalesce(beschreibung, [])\n  }\n': REFERENZEN_QUERY_RESULT;
    '\n  *[_type == "stimme"] | order(reihenfolge asc){\n    _id,\n    zitat,\n    name,\n    rolle,\n    portrait { ..., alt, bildunterschrift, asset }\n  }\n': STIMMEN_QUERY_RESULT;
    '\n  *[_type == "frage"] | order(reihenfolge asc){\n    _id,\n    frage,\n    "antwort": coalesce(antwort, [])\n  }\n': FRAGEN_QUERY_RESULT;
    '\n  *[_id == "startseite"][0]{\n    kennzeichnung,\n    ueberschrift,\n    hervorhebung,\n    einleitung,\n    hauptaktion { beschriftung, ziel },\n    nebenaktion { beschriftung, ziel },\n    "kennzahlen": coalesce(kennzahlen[] { _key, wert, label, erlaeuterung }, []),\n    ausgangslage { kennzeichnung, titel, text },\n    "maengel": coalesce(maengel, []),\n    loesung { kennzeichnung, titel, text },\n    "vorteile": coalesce(vorteile[] { _key, titel, text }, []),\n    branchenKopf { kennzeichnung, titel, text },\n    leistungenKopf { kennzeichnung, titel, text },\n    ablaufKopf { kennzeichnung, titel, text },\n    referenzenKopf { kennzeichnung, titel, text },\n    medienKopf { kennzeichnung, titel, text },\n    medienAnzeigen,\n    schlussKopf { kennzeichnung, titel, text },\n    schlussAktion { beschriftung, ziel },\n    seo { titel, beschreibung, bild { ..., alt, bildunterschrift, asset }, vonSucheAusschliessen }\n  }\n': STARTSEITE_QUERY_RESULT;
    '\n  *[_id == "leistungsseite"][0]{\n    kopf { kennzeichnung, titel, text },\n    preishinweis,\n    ablaufKopf { kennzeichnung, titel, text },\n    fragenKopf { kennzeichnung, titel, text },\n    seo { titel, beschreibung, bild { ..., alt, bildunterschrift, asset }, vonSucheAusschliessen }\n  }\n': LEISTUNGSSEITE_QUERY_RESULT;
    '\n  *[_id == "referenzseite"][0]{\n    kopf { kennzeichnung, titel, text },\n    platzhalterHinweis,\n    seo { titel, beschreibung, bild { ..., alt, bildunterschrift, asset }, vonSucheAusschliessen }\n  }\n': REFERENZSEITE_QUERY_RESULT;
    '\n  *[_id == "ueberSeite"][0]{\n    kopf { kennzeichnung, titel, text },\n    portrait { ..., alt, bildunterschrift, asset },\n    "text": coalesce(text, []),\n    "grundsaetze": coalesce(grundsaetze[] { _key, titel, text }, []),\n    seo { titel, beschreibung, bild { ..., alt, bildunterschrift, asset }, vonSucheAusschliessen }\n  }\n': UEBER_SEITE_QUERY_RESULT;
    '\n  *[_id == "kontaktseite"][0]{\n    kopf { kennzeichnung, titel, text },\n    formularHinweis,\n    "ablauf": coalesce(ablauf, []),\n    seo { titel, beschreibung, bild { ..., alt, bildunterschrift, asset }, vonSucheAusschliessen }\n  }\n': KONTAKTSEITE_QUERY_RESULT;
    '\n  *[_type == "rechtstext" && slug.current == $slug][0]{\n    titel,\n    "slug": slug.current,\n    stand,\n    "inhalt": coalesce(inhalt, []),\n    seo { titel, beschreibung, bild { ..., alt, bildunterschrift, asset }, vonSucheAusschliessen }\n  }\n': RECHTSTEXT_QUERY_RESULT;
    '\n  *[_type == "rechtstext" && defined(slug.current)]{ "slug": slug.current }\n': RECHTSTEXT_SLUGS_QUERY_RESULT;
  }
}
